/**
 * Shared type definitions
 * 
 * These types define the core data structures used throughout the app.
 * By centralizing them here, we ensure consistency and avoid circular imports.
 */

/**
 * A student in the class.
 */
export type Student = {
  id: string;
  firstName: string;
  lastName: string;
  gender: string;
  friendIds: string[];
};

/**
 * A group that students can be assigned to.
 */
export type Group = {
  id: string;        // Unique identifier (generated by uid())
  name: string;      // Editable label shown to user
  capacity: number | null; // Max students allowed, null = unlimited
  memberIds: string[]; // IDs of students currently in this group
};

/**
 * UI mode for creating groups.
 */
export type Mode = 'COUNT' | 'SIZE';